project:
  type: website

website:
  title: "sidestreams"
  favicon: tw_logo.png
  navbar:
    left:
      - text: "Posts"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Sources"
        href: sources.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual