on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Install Required R Packages
        run: |
          Rscript -e "install.packages('yaml')"
          Rscript -e "install.packages('rmarkdown')"
          Rscript -e "install.packages('knitr')"
          Rscript -e "install.packages('tidywater')"
          Rscript -e "install.packages('tidyverse')"
          Rscript -e "install.packages('curl')"
          Rscript -e "install.packages('base64enc')"
          Rscript -e "install.packages('bslib')"
          Rscript -e "install.packages('cachem')"
          Rscript -e "install.packages('cli')"
          Rscript -e "install.packages('digest')"
          Rscript -e "install.packages('evaluate')"
          Rscript -e "install.packages('fastmap')"
          Rscript -e "install.packages('fontawesome')"
          Rscript -e "install.packages('fs')"
          Rscript -e "install.packages('glue')"
          Rscript -e "install.packages('highr')"
          Rscript -e "install.packages('htmltools')"
          Rscript -e "install.packages('jquerylib')"
          Rscript -e "install.packages('jsonlite')"
          Rscript -e "install.packages('lifecycle')"
          Rscript -e "install.packages('memoise')"
          Rscript -e "install.packages('mime')"
          Rscript -e "install.packages('R6')"
          Rscript -e "install.packages('rappdirs')"
          Rscript -e "install.packages('rlang')"
          Rscript -e "install.packages('sass')"
          Rscript -e "install.packages('tinytex')"
          Rscript -e "install.packages('textshaping')"
          Rscript -e "install.packages('xfun')"

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
          packages: |
            any::rmarkdown
            any::tidyverse
            any::tidywater

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}